services:
  apache:
    build: 
      context: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./ci-application:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    build: 
      context: ./docker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: